### ISSUE TITLE
handle errors while fetching stock price

### ISSUE THREAD

**Issue by hussu010** [hussu010/Stock-Notifier#12]

**Comment by SanamShivakoti23** [comment]
I think it will be better not to let the user create alert notes for the searched symbol for those data points that are unavailable. So, based on this logic, I have tried to implement the condition. But it still has a bug, so I want to request that you review the code to fix the bug. I want your help on this issue.

**Comment by hussu010** [comment]
closed by https://github.com/hussu010/Stock-Notifier/pull/7/commits/ac52de19cb69cb17f484fe1cecb581d6dfb646d9
